services:
  - type: web
    name: stremio-m3u-addon
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: TMDB_API_KEY
        sync: false
      - key: RENDER_EXTERNAL_URL
        sync: false
      - key: REFRESH_HOURS
        value: "6"
